version: "3.7"
services:
  rabbitmq:
    image: order-service:latest
    container_name: 'order-service'
    restart: always
      - ORDER_QUEUE_URI=amqps://bestbuybusservice.servicebus.windows.net/  
      - ORDER_QUEUE_USERNAME=sender
      - ORDER_QUEUE_PASSWORD=mM4pJeok6bKD4pXzD6qzFBrIaxDtJY6aA+ASbLOxEHA=
      - ORDER_QUEUE_NAME=orders
      - ORDER_QUEUE_TRANSPORT=tls
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services
networks:
  backend_services:
    driver: bridge
